[package]
name = "velocity"
version = "0.1.0"
authors = ["Adrian Sampson <adrian@radbox.org>"]

[[bin]]
name = "vel"
path = "src/main.rs"

[dependencies]
walkdir = "1"
termion = "1"
textwrap = "0"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
